### ISSUE TITLE
skip one of the sessions

### ISSUE THREAD

**Issue by qasim85** [poldracklab/fitlins#244]
Hello everyone
I  have  pre and post sessions, but I am only  interested in pre sessions. Is there a way to skip post sessions ?

Thanks and best
Qasim

**Comment by adelavega** [comment]
Are you specifying your own BIDS Stats Model JSON file? If so you should be able to add to to the `Input` section `Session`: `1`.

**Comment by qasim85** [comment]
Thank you so much  for thee reply. So would it be something like this below ?


"Input": {
        "task": "novelfaces"
        "Session": 1
    },
    "Steps": [
        {
            "Level": "run",
....


Thanks again

best
Qasim

**Comment by effigies** [comment]
Session labels are alphanumeric, rather than numeric, but otherwise, that looks basically right

```YAML
  "Input": {
    "task": "novelfaces",
    "session": "1"
  },
  "Steps": [
    {
      "Level": "run",
....
```
